Mejoras
Toma el valor de la fecha de llegada y reemplaza por la variable fija actual
informacionEntrega = "entrega de 3 a 4 semanas a partir de la fecha de compra"


En el archivo htmlResponseExample.html se muestra un ejemplo de la etiqueta:
            </script><div class="opcionForm idx1" style=""><strong class="tituloProducto">Libro Nuevo</strong><p class="stock">
                                    Quedan 15 unidades
                            </p><strong class="precio">$ 63.00</strong><form action="/carro/agregar"><input type="hidden" name="c_producto" value="2562376"><input type="hidden" name="c_proveedor" value="3862"><button id="addToCart" class="button button-secondary">Comprar</button></form><div class="tiempoEnvio"><div class="diaEnvio"><div><span data-solo="0">
                    Llega entre <strong style="color: green">el 29 May</strong> y <strong style="color: green">el 03 Jun</strong><span class="detalle-direccion-envio"> a <strong>CUAUHTÉMOC, Ciudad de México</strong>. <a href="javascript:void(0)" onclick="selectDireccion()" class="link-seleccionar-ubicacion">Seleccionar ubicación</a></span></span></div></div></div></div></div><div class="book-tools"><div><label onclick="javascript:$('#agregar-deseo button').click()"><i class="far fa-heart margin-right-10"></i>Agregar a lista de deseos</label><div style="display:none"><form id="agregar-deseo" class="agregar-deseo" action="/v2/u"><input type="hidden" name="rto" value="/pb/2510172"><button class="padding-left-xs-10 float-right no-button" type="submit"><div class="menu-icon-wrapper"><div class="margin-top-xs-10 font-color-bl overflow-visible"><i class="far fa-heart fa-lg margin-right-10"></i>Agregar a lista de deseos</div></div></button></form><!-- MODAL lista de deseos --><div class="modal modal-deseo-contenido dialog-box"><i class="cerrar fas fa-times color-gray fa-lg"></i><p class="font-size-medium margin-top-xs-10 text-align-center">Elige la lista en la que quieres agregar tu producto o crea una <span class="nuevaLista color-primary cursor-pointer">nueva lista</span></p><form class="agregandoaLista margin-top-20 margin-bottom-20 display-inline-block width-100" action="/v2/lista-deseos"><input type="hidden" name="action" value="add_product"><input type="hidden" name="id_producto" value="2510172"><input type="hidden" name="precio" value=""><!-- <div class="row"><div class="col-xs-12 col-md-6"> --><select class="margin-left-0 cursor-pointer width-100" name="id_lista"><option value="-1">Cargando, espera por favor...</option></select><!-- </div><div class="col-xs-12 col-md-6"> --><button class="agregarEnLista button button-secondary margin-right-0 margin-top-10 font-size-small width-100" type="button">Agregar</button><!-- </div></div> --></form><form class="creandounaLista display-none margin-top-20" action="/v2/lista-deseos"><input type="hidden" name="action" value="create_add_product"><input type="hidden" name="id_producto" value="2510172"><input type="hidden" name="precio" value=""><!-- <div class="row"><div class="col-xs-12 col-md-6"> --><input class="margin-left-0" type="text" name="nombre" placeholder="Nombre nueva lista"><!-- </div><div class="col-xs-12 col-md-6"> --><button class="agregarEnLista button button-secondary margin-right-0 margin-top-10 font-size-small width-100" type="button">Crear y Agregar</button><!-- </div></div> --></form><p class="agregadoAlCarro font-size-normal text-align-center" style="display:none;"><span>✓</span> Producto agregado <strong>correctamente</strong> a la lista de deseos.</p><a class="margin-top-20" href="/u" title="Ir a Mis Listas">Ir a Mis Listas</a></div><!-- /MODAL lista de deseos --><script type="text/javascript">

Que es donde viene el campo de fecha de llegada.